# Configure Cloudflare Pages

name = "hosting-cloudflare-pages"
pages_build_output_dir = "public"

[vars]
DART_SASS_VERSION = "1.98.0"
GO_VERSION = "1.26.1"
HUGO_VERSION = "0.158.0"
NODE_VERSION = "24.14.0"
TZ = "Europe/Oslo"
